@testset "Architecture discovery adjoint and sparse recovery" begin
    dimer = Bnc(
        N=reshape([1, 1, -1], 1, 3),
        x_sym=[:A, :B, :AB],
        q_sym=[:tA, :tB],
        K_sym=[:Kd1],
    )
    totals = [0.2 1.0; 0.7 1.0; 2.0 1.0]
    observable = reshape([0.0, 0.0, 1.0], 1, 3)
    targets = zeros(3, 1)
    logkd = [0.2]
    evaluation = architecture_loss_gradient(
        dimer, totals, targets, observable, logkd)
    step = 1e-5
    plus = architecture_loss_gradient(
        dimer, totals, targets, observable, logkd .+ step;
        scales=evaluation.scales,
    ).data_loss
    minus = architecture_loss_gradient(
        dimer, totals, targets, observable, logkd .- step;
        scales=evaluation.scales,
    ).data_loss
    finite_difference = (plus - minus) / (2step)
    @test isapprox(evaluation.gradient[1], finite_difference; rtol=1e-6, atol=1e-8)

    # Candidate library: AA, AB, BB. The data are generated by AB alone.
    library = Bnc(
        N=[
            2 0 -1 0 0
            1 1 0 -1 0
            0 2 0 0 -1
        ],
        x_sym=[:A, :B, :AA, :AB, :BB],
        q_sym=[:tA, :tB],
        K_sym=[:Kd1, :Kd2, :Kd3],
    )
    values = exp10.([-1.0, -0.33, 0.33, 1.0])
    library_totals = reduce(vcat, ([a b] for a in values for b in values))
    bound_atoms = [
        0.0 0.0 2.0 1.0 0.0
        0.0 0.0 0.0 1.0 2.0
    ]
    truth = architecture_loss_gradient(
        library,
        library_totals,
        zeros(16, 2),
        bound_atoms,
        log10.([1e4, 1.0, 1e4]),
    ).predictions
    recovered = discover_architecture(
        library, library_totals, truth, bound_atoms)

    @test recovered.active == Bool[false, true, false]
    @test recovered.affinity[2] > 100 * recovered.affinity[1]
    @test recovered.affinity[2] > 100 * recovered.affinity[3]
    @test recovered.fit_loss < 1e-4
end
