@testset "Architecture discovery adjoint and sparse recovery" begin
    dimer = Bnc(
        N=reshape([1, 1, -1], 1, 3),
        x_sym=[:A, :B, :AB],
        q_sym=[:tA, :tB],
        K_sym=[:Kd1],
    )
    totals = [0.2 1.0; 0.7 1.0; 2.0 1.0]
    observable = reshape([0.0, 0.0, 1.0], 1, 3)
    targets = zeros(3, 1)
    logkd = [0.2]
    evaluation = architecture_loss_gradient(
        dimer, totals, targets, observable, logkd)
    step = 1e-5
    plus = architecture_loss_gradient(
        dimer, totals, targets, observable, logkd .+ step;
        scales=evaluation.scales,
    ).data_loss
    minus = architecture_loss_gradient(
        dimer, totals, targets, observable, logkd .- step;
        scales=evaluation.scales,
    ).data_loss
    finite_difference = (plus - minus) / (2step)
    @test isapprox(evaluation.gradient[1], finite_difference; rtol=1e-6, atol=1e-8)

    @testset "Trajectory records matching parameter and loss states" begin
        target = evaluation.predictions
        options = (epochs=4, debias_epochs=2, active_threshold=0.0)
        baseline = discover_architecture(dimer, totals, target, observable; options...)
        trace = NamedTuple[]
        recorded = discover_architecture(dimer, totals, target, observable;
            options..., callback=state -> push!(trace, state))
        @test recorded.kd == baseline.kd
        @test recorded.fit_loss == baseline.fit_loss
        @test [(s.phase, s.step) for s in trace] ==
            vcat([(:penalized, i) for i in 0:4], [(:refit, i) for i in 0:2])
        @test first(trace).logkd == [0.0]
        @test exp10.(last(trace).logkd) == recorded.kd
        for state in trace
            check = architecture_loss_gradient(
                dimer, totals, target, observable, state.logkd;
                scales=recorded.output_scales)
            @test isapprox(check.data_loss, state.data_loss; rtol=1e-7, atol=1e-12)
            penalty = state.phase == :penalized ? 1e-3 * sum(exp10.(-state.logkd)) : 0.0
            @test state.objective ≈ state.data_loss + penalty
        end
    end

    # Candidate library: AA, AB, BB. The data are generated by AB alone.
    library = Bnc(
        N=[
            2 0 -1 0 0
            1 1 0 -1 0
            0 2 0 0 -1
        ],
        x_sym=[:A, :B, :AA, :AB, :BB],
        q_sym=[:tA, :tB],
        K_sym=[:Kd1, :Kd2, :Kd3],
    )
    values = exp10.([-1.0, -0.33, 0.33, 1.0])
    library_totals = reduce(vcat, ([a b] for a in values for b in values))
    bound_atoms = [
        0.0 0.0 2.0 1.0 0.0
        0.0 0.0 0.0 1.0 2.0
    ]
    truth = architecture_loss_gradient(
        library,
        library_totals,
        zeros(16, 2),
        bound_atoms,
        log10.([1e4, 1.0, 1e4]),
    ).predictions
    recovered = discover_architecture(
        library, library_totals, truth, bound_atoms)

    @test recovered.active == Bool[false, true, false]
    @test recovered.affinity[2] > 100 * recovered.affinity[1]
    @test recovered.affinity[2] > 100 * recovered.affinity[3]
    @test recovered.fit_loss < 1e-4

    # Equal B/C totals and the summed AB+AC readout make the two reactions
    # observationally interchangeable. The tiny deterministic default stagger
    # should escape the dense symmetric stationary point and return one of them.
    ambiguous = Bnc(
        N=[
            1 1 0 -1 0
            1 0 1 0 -1
        ],
        x_sym=[:A, :B, :C, :AB, :AC],
        q_sym=[:tA, :tB, :tC],
        K_sym=[:Kd1, :Kd2],
    )
    ambiguous_totals = reduce(vcat, (
        [a 1.0 1.0] for a in exp10.(range(-1.5, 1.5; length=16))))
    summed_complexes = reshape([0.0, 0.0, 0.0, 1.0, 1.0], 1, :)
    ambiguous_targets = architecture_loss_gradient(
        ambiguous,
        ambiguous_totals,
        zeros(16, 1),
        summed_complexes,
        log10.([1.0, 1e12]),
    ).predictions
    symmetry_broken = discover_architecture(
        ambiguous, ambiguous_totals, ambiguous_targets, summed_complexes)

    @test count(symmetry_broken.active) == 1
    @test symmetry_broken.fit_loss < 1e-5

    branched = Bnc(
        N=[
            1 1 0 -1  0  0  0  0
            0 1 0  1 -1  0  0  0
            0 1 0  0  1 -1  0  0
            1 0 1  0  0  0 -1  0
            0 0 1  0  0  0  1 -1
        ],
        x_sym=[:A, :B, :C, :AB, :AB2, :AB3, :AC, :AC2],
        q_sym=[:tA, :tB, :tC],
        K_sym=[:Kd1, :Kd2, :Kd3, :Kd4, :Kd5],
    )
    levels = exp10.([-0.75, -0.25, 0.25, 0.75])
    branched_totals = reduce(vcat, (
        [a b c] for a in levels for b in levels for c in levels))
    branch_outputs = [
        0.0 0.0 0.0 1.0 2.0 3.0 0.0 0.0
        0.0 0.0 0.0 0.0 0.0 0.0 1.0 2.0
    ]
    branch_targets = architecture_loss_gradient(
        branched,
        branched_totals,
        zeros(64, 2),
        branch_outputs,
        log10.([0.8, 0.35, 1e6, 1.7, 1e6]),
    ).predictions
    branch_fit = discover_architecture(
        branched, branched_totals, branch_targets, branch_outputs)

    @test branch_fit.active == Bool[true, true, false, true, false]
    @test branch_fit.fit_loss < 1e-5

    order_library_N = zeros(Int, 5, 7)
    order_outputs = zeros(3, 7)
    for order in 1:5
        order_library_N[order, 1] = 1
        order_library_N[order, 2] = order
        order_library_N[order, order + 2] = -1
        order_outputs[:, order + 2] .= (1, order, order^2)
    end
    order_library = Bnc(
        N=order_library_N,
        x_sym=[:E, :B, :EB, :EB2, :EB3, :EB4, :EB5],
        q_sym=[:tE, :tB],
        K_sym=[:Kd1, :Kd2, :Kd3, :Kd4, :Kd5],
    )
    order_totals = reduce(vcat, (
        [e b]
        for e in (0.3, 1.0, 3.0)
        for b in exp10.(range(-2.0, 2.0; length=20))
    ))
    order_targets = architecture_loss_gradient(
        order_library,
        order_totals,
        zeros(60, 3),
        order_outputs,
        log10.([1e6, 1e6, 1e6, 1.0, 1e6]),
    ).predictions
    order_fit = discover_architecture(
        order_library, order_totals, order_targets, order_outputs)

    @test order_fit.active == Bool[false, false, false, true, false]
    @test order_fit.fit_loss < 1e-5
end
