# === ROP periodic-table layer (LOCAL OVERLAY) exports =============================
export scan_parameter_1d, scan_parameter_2d
export SampledReactionOrderField, ROFieldGridLimitExceeded
export sample_reaction_order_field
export ROInputDomain2D, ROAffineLabel2D, ROCell2D, ROFacet2D
export ROSingularStratum2D, ROCellComplex2D, ROPointClassification2D
export ROCellComplexBuildLimits, ROCellComplexLimitExceeded
export build_ro_cell_complex, classify_ro_cell_complex_point
export RO_CELL_COMPLEX_3D_VERSION, RO_CELL_COMPLEX_3D_EVIDENCE_SCOPE
export ROInputDomain3D, ROAffineLabel3D
export ROCellSpec3D, ROInterfaceAnnotation3D, ROCellComplex3DTolerances
export ROCellComplex3DLimits, ROCellComplex3DConstructionError
export ROCellComplex3DLimitExceeded, ROCellComplex3DRankAmbiguity
export ROCellComplex3DSliver, ROCellComplex3DExactDimensionMismatch
export ROCellComplex3DOverlap
export ROCellComplex3DClosureError, ROVertex3D, RORidge3D, ROFacet3D
export ROCell3D, ROStratum3D, ROCellComplex3DCertificate, ROCellComplex3D
export build_ro_cell_complex_3d, validate_ro_cell_complex_3d
export ROAffineInputChart, ro_source_coordinate_count
export ro_control_coordinate_count, map_ro_source_coordinates
export pullback_ro_matrix, pullback_ro_tensor
export RO_NONLINEAR_INPUT_CHART_VERSION, RO_NONLINEAR_INPUT_CHART_SCOPE
export RONonlinearChartLimitExceeded, RONonlinearChartImmersionRejected
export RONonlinearChartLimits, RONonlinearInputChart
export RONonlinearChartEvaluation, RONonlinearSourceDerivatives
export RONonlinearHessianPullback
export evaluate_ro_nonlinear_input_chart
export map_ro_nonlinear_source_coordinates, ro_nonlinear_source_jacobian
export pullback_ro_nonlinear_matrix, pullback_ro_nonlinear_tensor
export pullback_ro_nonlinear_hessian, replay_ro_nonlinear_input_chart
export RO_OBSERVABLE_CHART_VERSION, RO_OBSERVABLE_CHART_SCOPE
export ROObservableChartLimitExceeded, ROObservableChartLimits
export RODeclarativeObservableChart
export ROAffineObservableChart, ROQuadraticObservableChart
export ro_source_observable_count, ro_derived_observable_count
export evaluate_ro_observables, compose_ro_observable_jet
export RO_POLYNOMIAL_EQUILIBRIUM_SYSTEM_VERSION
export RO_REGULAR_SHEET_PATCH_VERSION, RO_REGULAR_SHEET_BRIDGE_VERSION
export RO_REGULAR_SHEET_PATCH_SCOPE, RO_REGULAR_SHEET_BRIDGE_SCOPE
export RORegularSheetLimitExceeded, RORegularSheetCertificationRejected
export RORegularSheetLimits, ROPolynomialTerm
export ROPolynomialEquilibriumSystem, validate_ro_polynomial_equilibrium_system
export ROExactInterval, ROExactMatrix, ROExactIntervalMatrix
export RORegularSheetPatchCertificate, RORegularSheetBridgeCertificate
export certify_ro_regular_sheet_patch, replay_ro_regular_sheet_patch
export validate_ro_regular_sheet_patch
export certify_ro_regular_sheet_bridge, replay_ro_regular_sheet_bridge
export validate_ro_regular_sheet_bridge
export RO_COMPLETE_REGULAR_ROOT_CENSUS_VERSION
export RO_COMPLETE_REGULAR_ROOT_CENSUS_SCOPE
export RORegularRootCensusLimitExceeded, RORegularRootCensusRejected
export RORegularRootCensusLimits, RORegularRootCensusCell
export ROCompleteRegularRootCensus
export certify_ro_complete_regular_root_census
export replay_ro_complete_regular_root_census
export validate_ro_complete_regular_root_census
export RO_SIMPLE_FOLD_EVENT_CENSUS_VERSION
export RO_SIMPLE_FOLD_EVENT_CENSUS_SCOPE
export ROFoldEventCensusLimitExceeded, ROFoldEventCensusRejected
export ROFoldEventCensusLimits, ROSimpleFoldEvent, ROFoldEventCensusCell
export ROCompleteSimpleFoldEventCensus
export certify_ro_complete_simple_fold_event_census
export replay_ro_complete_simple_fold_event_census
export validate_ro_complete_simple_fold_event_census
export RO_SIMPLE_FOLD_BRANCH_INCIDENCE_VERSION
export RO_SIMPLE_FOLD_BRANCH_INCIDENCE_SCOPE
export ROFoldBranchIncidenceLimitExceeded, ROFoldBranchIncidenceRejected
export ROFoldBranchIncidenceLimits, ROFoldHalfBranchIncidence
export ROSimpleFoldBranchIncidenceCertificate
export ro_fold_branch_coordinate_system
export certify_ro_simple_fold_branch_incidence
export replay_ro_simple_fold_branch_incidence
export validate_ro_simple_fold_branch_incidence
export RO_SIMPLE_SPECTRAL_HOPF_EVENT_CENSUS_VERSION
export RO_SIMPLE_SPECTRAL_HOPF_EVENT_CENSUS_SCOPE
export ROSpectralHopfEventCensusLimitExceeded
export ROSpectralHopfEventCensusRejected
export ROSpectralHopfEventCensusLimits, ROSimpleSpectralHopfEvent
export ROSpectralHopfEventCensusCell
export ROCompleteSimpleSpectralHopfEventCensus
export certify_ro_complete_simple_spectral_hopf_event_census
export replay_ro_complete_simple_spectral_hopf_event_census
export validate_ro_complete_simple_spectral_hopf_event_census
export RO_HOPF_LYAPUNOV_SEED_VERSION
export RO_FIRST_LYAPUNOV_HOPF_EVENT_VERSION
export RO_COMPLETE_NONDEGENERATE_HOPF_CENSUS_VERSION
export RO_FIRST_LYAPUNOV_FORMULA_VERSION
export RO_HOPF_EIGENVECTOR_NORMALIZATION_VERSION
export RO_COMPLETE_NONDEGENERATE_HOPF_CENSUS_SCOPE
export ROHopfLyapunovLimitExceeded, ROHopfLyapunovRejected
export ROHopfLyapunovLimits, ROHopfLyapunovSeed
export ROFirstLyapunovHopfEvent, ROCompleteNondegenerateHopfCensus
export certify_ro_complete_nondegenerate_hopf_census
export replay_ro_complete_nondegenerate_hopf_census
export validate_ro_complete_nondegenerate_hopf_census
export RO_HOPF_PERIODIC_ORBIT_GERM_EVENT_VERSION
export RO_COMPLETE_HOPF_PERIODIC_ORBIT_GERM_CENSUS_VERSION
export RO_HOPF_PERIODIC_ORBIT_GERM_THEOREM_VERSION
export RO_HOPF_CROSSING_ORIENTATION_FORMULA_VERSION
export RO_COMPLETE_HOPF_PERIODIC_ORBIT_GERM_CENSUS_SCOPE
export ROHopfPeriodicOrbitGermLimitExceeded
export ROHopfPeriodicOrbitGermRejected
export ROHopfPeriodicOrbitGermLimits
export ROHopfPeriodicOrbitGermEvent
export ROCompleteHopfPeriodicOrbitGermCensus
export certify_ro_complete_hopf_periodic_orbit_germ_census
export replay_ro_complete_hopf_periodic_orbit_germ_census
export validate_ro_complete_hopf_periodic_orbit_germ_census
export RO_EXACT_REAL_FOURIER_SERIES_VERSION
export RO_EXACT_POLYNOMIAL_PERIODIC_FOURIER_AUDIT_VERSION
export RO_EXACT_WEIGHTED_L1_FOURIER_NORM_VERSION
export RO_EXACT_POLYNOMIAL_PERIODIC_FOURIER_AUDIT_SCOPE
export ROPeriodicFourierLimitExceeded, ROPeriodicFourierRejected
export ROPeriodicFourierLimits, ROExactRealFourierSeries
export ROExactPolynomialPeriodicFourierAudit
export validate_ro_exact_real_fourier_series
export audit_ro_exact_polynomial_periodic_fourier_residual
export replay_ro_exact_polynomial_periodic_fourier_residual
export validate_ro_exact_polynomial_periodic_fourier_residual
export RO_POLYNOMIAL_DYNAMICS_BINDING_VERSION
export RO_BRANCH_INDEXED_REGULAR_FIELD_VERSION
export RO_BRANCH_PATCH_STABILITY_POLICY_VERSION
export RO_BRANCH_LOG_RESPONSE_POLICY_VERSION
export RO_BRANCH_INDEXED_REGULAR_FIELD_SCOPE
export ROBranchIndexedFieldLimitExceeded
export ROBranchIndexedFieldCertificationRejected
export ROBranchIndexedFieldLimits, ROPolynomialDynamicsBinding
export ROBranchPatchEvidence, ROBranchComponentEvidence
export ROBranchSeparationEvidence, ROMultistabilityWitnessEvidence
export ROBranchIndexedRegularField
export validate_ro_polynomial_dynamics_binding
export certify_ro_branch_indexed_regular_field
export replay_ro_branch_indexed_regular_field
export validate_ro_branch_indexed_regular_field
export RODifferentialLimitExceeded, ROIntegrabilityPairSummary
export RODiscreteIntegrabilityCertificate, ROFiniteDifferenceCurvature
export ROSynergyPairSummary, ROFiniteWindowSynergy
export certify_sampled_ro_integrability, estimate_sampled_ro_curvature
export classify_finite_window_synergy
export RO_FIELD_EVIDENCE_IDENTITY_VERSION
export RO_SCIENTIFIC_SOURCE_IDENTITY_VERSION
export RO_LOCAL_IDENTIFIABILITY_VERSION
export RO_DELTA_METHOD_UNCERTAINTY_VERSION
export RO_SYNTHETIC_COVERAGE_VERSION, RO_UNCERTAINTY_POPULATION_VERSION
export RO_INTERVAL_COORDINATE_DEFINITION_VERSION
export RO_LOCAL_IDENTIFIABILITY_SCOPE
export ROUncertaintyLimits, ROUncertaintyLimitExceeded
export ROCovarianceNumericallyAmbiguous
export ROFieldEvidenceIdentity, ro_field_evidence_identity_payload
export ROScientificSourceIdentity, ro_scientific_source_identity_payload
export ro_scientific_source_identity_sha256, ROUncertaintyPartition
export ROPopulationPolicy, ROEnsemblePopulationPolicy
export ROCertifiedIntervalPopulationPolicy
export ro_population_count, ro_population_policy_kind
export ro_population_policy_payload
export ROLocalIdentifiabilityAnalysis, RODeltaMethodCovariance
export ROSyntheticCoverageEvidence, ROUncertaintyPopulationArtifact
export analyze_ro_local_identifiability, propagate_ro_delta_covariance
export evaluate_ro_synthetic_coverage_fixture
export summarize_ro_uncertainty_population
export validate_ro_local_identifiability_analysis
export validate_ro_delta_method_covariance
export validate_ro_synthetic_coverage_evidence
export validate_ro_uncertainty_population_artifact
export ROStratifiedFieldLimits, ROStratifiedFieldLimitExceeded
export RORegularExtensionIntegrabilityCertificate, ROJointJacobianQuery2D
export RODirectionalDerivativeGenerators2D
export certify_ro_regular_extension_integrability
export query_ro_stratified_jacobian, ro_directional_derivative_generators
export query_ro_stratified_directional_derivatives
export RO_REGULAR_EXTENSION_INTEGRABILITY_3D_VERSION
export RO_REGULAR_EXTENSION_INTEGRABILITY_3D_SCOPE
export ROStratifiedField3DLimits, ROStratifiedField3DLimitExceeded
export ROStratifiedField3DValidationError, ROIntegrabilityObstruction3D
export RORegularExtensionIntegrabilityCertificate3D
export certify_ro_regular_extension_integrability_3d
export validate_ro_regular_extension_integrability_certificate_3d
export RO_SINGULAR_SELECTION_VERSION, RO_SINGULAR_SELECTION_POLICY_VERSION
export RO_SINGULAR_STABILITY_EVIDENCE_VERSION
export RO_SINGULAR_REACHABILITY_EVIDENCE_VERSION
export RO_SINGULAR_POPULATION_RECEIPT_VERSION
export RO_SINGULAR_BRANCH_IDENTITY_VERSION
export RO_SINGULAR_CANDIDATE_PAYLOAD_VERSION
export RO_SINGULAR_SELECTION_SCOPE, ROSingularSelectionLimitExceeded
export ROSingularSelectionLimits, ROSingularBranchCandidate
export ROSingularSelectionPolicy, ROSingularSelectionCertificate
export ROSingularStabilityEvidence, ROSingularReachabilityEvidence
export ROSingularCandidatePopulationReceipt
export ro_singular_branch_identity_sha256
export build_ro_singular_candidate_population_receipt
export certify_ro_singular_branch_selection
export RO_SPARSE_POLICY_VERSION, RO_SPARSE_EVIDENCE_SCOPE
export ROSparseSamplingLimitExceeded, ROSparseSamplingLimits
export ROSparseSamplingPlan, ROSparseEvaluation, ROSparsePointRequest
export ROSparseSample, ROSparseIndexRecord, ROSparseUnresolvedRegion
export ROSparseSamplingResult, ro_sparse_valid, ro_sparse_invalid
export nested_clenshaw_curtis_nodes, incremental_clenshaw_curtis_nodes
export smolyak_is_downward_closed, smolyak_admissible_frontier
export ro_sparse_sampling_spec, ro_sparse_sampling_spec_sha256
export ro_sparse_adaptive_plan_sha256, adaptive_sparse_ro_field
export RO_SPARSE_RO_CHANNEL_PLAN_VERSION, RO_SPARSE_RO_STATE_VERSION
export RO_SPARSE_RO_BATCH_VERSION, RO_SPARSE_RO_RESULT_VERSION
export ROSparseROChannelPlanV2, ROSparseAdaptiveStateV2
export ROSparseIndexBatchV2, ROSparseSamplingResultV2
export ro_sparse_ro_channel_order_v2
export ro_sparse_portable_token_byte_limit_v2
export ro_sparse_ro_channel_plan_v2_payload, ro_sparse_state_v2_payload
export ro_sparse_index_batch_v2_payload, ro_sparse_result_v2_payload
export ro_sparse_ordered_evaluation_v2
export validate_ro_sparse_ro_channel_plan_v2, validate_ro_sparse_state_v2
export validate_ro_sparse_index_batch_v2, validate_ro_sparse_result_v2
export initialize_ro_sparse_state_v2, prepare_ro_sparse_index_batch_v2
export commit_ro_sparse_index_batch_v2, finalize_ro_sparse_state_v2
export adaptive_sparse_ro_field_v2
export restore_ro_sparse_ro_channel_plan_v2, restore_ro_sparse_state_v2
export restore_ro_sparse_index_batch_v2, restore_ro_sparse_result_v2
export RO_DYNAMIC_PROTOCOL_TRACE_VERSION
export RO_DYNAMIC_HYSTERESIS_ANALYSIS_VERSION
export RO_STATIC_MULTIROOT_EVIDENCE_VERSION
export RO_DYNAMIC_BRANCH_EVIDENCE_VERSION
export RO_POLYNOMIAL_VECTOR_FIELD_VERSION
export RO_DYNAMIC_HYSTERESIS_EVIDENCE_SCOPE
export RO_DYNAMIC_HYSTERESIS_ANALYZER_POLICY_SHA256
export RODynamicEvidenceLimits, RODynamicEvidenceLimitExceeded
export RODynamicSwitchEvent, RODynamicProtocolTrace, RODynamicBranchEvidence
export RODynamicHysteresisAnalysis, ROStaticMultirootEvidence
export ROPolynomialVectorField, ro_polynomial_vector_field
export validate_ro_polynomial_vector_field
export ro_dynamic_protocol_identity_payload
export ro_dynamic_protocol_identity_sha256
export certify_ro_dynamic_branch_evidence
export validate_ro_dynamic_branch_evidence
export certify_ro_equilibrium_branch_evidence
export validate_ro_equilibrium_branch_evidence
export validate_ro_dynamic_hysteresis_analysis
export analyze_dynamic_hysteresis, analyze_static_multiroot
export validate_ro_static_multiroot_evidence
export RO_DYNAMIC_PROTOCOL_SPEC_VERSION
export RO_MODEL_BACKED_TRAJECTORY_EVIDENCE_VERSION
export RO_MODEL_BACKED_TRAJECTORY_EVIDENCE_SCOPE
export RODynamicTrajectoryLimits, RODynamicTrajectoryLimitExceeded
export RODynamicTrajectorySolverFailure
export RODynamicTrajectoryStateBoundsExceeded
export RODynamicProtocolSpec, ROModelBackedTrajectoryEvidence
export ro_dynamic_protocol_spec, validate_ro_dynamic_protocol_spec
export simulate_ro_model_backed_trajectory
export validate_ro_model_backed_trajectory_evidence
export parse_linear_combination
export ChangePaths, get_change_graph
export change_kind, change_label, change_qK_indices, change_qK_signs
export get_behavior_families, summary_behavior_families
export get_vertex_rop_coords, get_edge_rop_segment, compute_rop_polyhedron
export get_ROP_plot_data
